routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>'serialNumber'],function(){
    //add language prefix
    Route::group(
        [
            'prefix' => LaravelLocalization::setLocale(),
            'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
        ], function(){


        //add middleware guest to all route
        Route::group(['middleware'=>'guest'],function(){
            //add namespace user to all route
            Route::group(['namespace'=>'User'],function(){
                //route to function that return login view
                Route::get('login','UserAuthController@login')->name('login');
                //route to function that handle users login
                Route::post('login','UserAuthController@do_login')->name('do_login');
                //route to function that return forget password view
                Route::get('forget/password','UserAuthController@forget_password')->name('forget_password');
                //route to function that handle create token for user
                Route::post('forget/password','UserAuthController@forget_password_post')->name('forget_password_post');
                //route to function that return reset password view
                Route::get('reset/password/{token}','UserAuthController@reset_password')->name('reset_password');
                //route to function that reset user password
                Route::post('reset/password/{token}','UserAuthController@reset_password_final')->name('reset_password_final');
            });
        });


        //assign middleware to all route
        Route::group(['middleware'=>'auth:web'],function(){
            //redirect route to dashboard
            Route::redirect('/','dashboard');

            //prefix all route with dashboard
            Route::group(['prefix'=>'dashboard'],function(){
                //route to return home view
                Route::get('/',function(){
                    return view('users.index',['title'=>trans('users.Dashboard')]);
                });

                //route to users resource
                Route::namespace('User')->group(function(){
                    Route::get('users/delete/{id}','UserController@destroy')->name('delete_users');
                    Route::resource('users','UserController');
                    //rotue to logout function that handle user logout

                    Route::any('logout','UserAuthController@logout')->name('logout');

                });
                //route to resource category
                Route::namespace('Category')->group(function(){
                    Route::get('categories/multi_add','CategoryController@multi_add')->name('multi_add');
                    Route::post('categories/multi_add','CategoryController@multi_store')->name('categories_multi_add_store');
                    Route::get('categories/multi_delete','CategoryController@multi_delete')->name('category_multi_delete');
                    Route::get('categories/delete/{id}','CategoryController@destroy')->name('delete_categories');
                    Route::resource('categories','CategoryController');
                });


                //route to resource products
                Route::namespace('Product')->group(function(){
                    Route::get('products/category','ProductController@getcategory')->name('getCategory');
                    Route::get('products/multi_add','ProductController@multi_add')->name('multi_add');
                    Route::post('products/multi_add','ProductController@multi_store')->name('products_multi_add_store');
                    Route::get('products/multi_delete','ProductController@multi_delete')->name('products_multi_delete');
                    Route::get('products/delete/{id}','ProductController@destroy')->name('delete_products');
                    Route::resource('products','ProductController');
                });


                //route to resource products
                Route::namespace('Order')->group(function(){
                    Route::get('orders/multi_add','OrderController@multi_add')->name('multi_add');
                    Route::post('orders/multi_add','OrderController@multi_store')->name('orders_multi_add_store');
                    Route::get('orders/delete/{id}','OrderController@destroy')->name('delete_orders');
                    Route::resource('orders','OrderController');
                });

            });
        });




    });
});
Route::get('notfound',function(){
    return view('users.notFound',['title'=>trans('users.Not Found')]);
})->name('notFound');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'serialNumber',
        'image',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    protected $appends = ['image_path'];
    public function getImagePathAttribute(){
        return asset('uploads/users/'.$this->image);
    }

    //function to get user name with first letter as capital letter
    public function getNameAttribute($value){
        return ucfirst($value);
    }
}

app/Http/Controllers/User/UserAuthController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Mail\UserResetPassword;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Validation\Rule;

class UserAuthController extends Controller
{
    //function to return login view
    public function login(){
        return view('users.login',['title'=>trans('users.Login')]);
    }

    //function to handle users login
    public function do_login(Request $request){
        $remember_me = $request->remember_me == 1 ? true : false;
        if(admin()->attempt(['email'=>$request->email,'password'=>$request->password],$remember_me)){
            session()->flash('success',trans('users.You Are Logged In Successfully'));
            return redirect(aurl());
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to handle user logout
    public function logout(){
        admin()->logout();
        session()->flash('success',trans('users.You Are Logged Out Successfully'));
        return redirect('login');
    }

    //function to return forget password view
    public function forget_password(){
        return view('users.forget_password',['title'=>trans('users.Forgot Password?')]);
    }

    //function to create token for user
    public function forget_password_post(Request $request){
        $user = User::where('email',$request->email)->first();
        if(!empty($user)){
            $token = app('auth.password.broker')->createToken($user);
            $data = DB::table('password_resets')->insert([
                'email'=>$user->email,
                'token'=>$token,
                'created_at'=>Carbon::now()
            ]);
            Mail::to($user->email)->send(new UserResetPassword(['data'=>$user,'token'=>$token]));
            session()->flash('success',trans('users.Reset Link Sent Successfully'));
            return back()->withInput();
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to return reset password view
    public function reset_password($token){
        $check_token = DB::table('password_resets')->where('token',$token)->where('created_at','>',Carbon::now()->subHours(2))->first();
        if(!empty($check_token)){
            return view('users.reset_password',['title'=>trans('users.Reset Password'),'data'=>$check_token]);
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to reset user password
    public function reset_password_final(Request $request,$token){
        $check_token = DB::table('password_resets')->where('token',$token)->where('created_at','>',Carbon::now()->subHours(2))->first();
        $request->validate([
            'email'=>['required',Rule::in($check_token->email)],
            'password'=>'required|confirmed|min:9',
            'password_confirmation'=>'required'
        ]);
        if(!empty($check_token)){
            $user = User::where('email',$check_token->email)->update([
                'email'=>$check_token->email,
                'password'=>bcrypt($request->password)
            ]);
            DB::table('password_resets')->where('email',$request->email)->delete();
            $serialNumber = SerialNumber();
            admin()->attempt(['email'=>$check_token->email,'password'=>$request->password,'serialNumber'=>$serialNumber],true);
            session()->flash('success',trans('users.Password Reset Successfully'));
            return redirect(aurl());
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserStore;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware(['permission:read_users'])->only('index');
        $this->middleware(['permission:create_users'])->only('create');
        $this->middleware(['permission:update_users'])->only('edit');
        $this->middleware(['permission:delete_users'])->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::whereRoleIs('admin')->get();
        return view('users.users.index',['title'=>trans('users.Users List'),'users'=>$users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.users.create',['title'=>trans('users.Add User')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStore $request)
    {
        $serialNumber = serialNumber();
        $data = $request->validated();
        if($request->image){
            Image::make($request->image)->resize(300,null,function($constraint){
                $constraint->aspectRatio();
            })->save(public_path('uploads/users/'.$request->image->hashName()));
            $data['image'] = $request->image->hashName();
        }
        if($request->password){
            $data['password'] = bcrypt($request->password);
        }
        $user = User::create($data);
        $user->attachRole('admin');
        $user->syncPermissions($request->permissions);
        session()->flash('success',trans('users.Data Saved Successfully'));
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('users.users.edit',['title'=>trans('users.User Edit'),'user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'name'=>'required|min:5',
            'email'=>['required',Rule::unique('users','email')->ignore($id,'id')],
            'password'=>'sometimes|nullable|min:9',
            'permissions'=>'required|array|min:1',
            'image'=>'mimes:jpeg,gif,jpg,png',
        ]);
        $user = User::find($id);
        if($request->has('password')){
            $data['password'] = bcrypt($request->password);
        }
        if($request->image){
            if($request->image !='default.png'){
                Storage::disk('public_uploads')->delete('users/'.$user->image);
            }

            Image::make($request->image)->resize(300,null,function($constraint){
                $constraint->aspectRatio();
            })->save(public_path('uploads/users/'.$request->image->hashName()));
            $data['image'] = $request->image->hashName();
        }
        $user->update($data);
        $user->syncPermissions($request->permissions);
        session()->flash('success',trans('users.Data Updated Successfully'));
        return redirect(aurl('users'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if($user->image!='default.png'){
            Storage::disk('public_uploads')->delete('users/'.$user->image);
        }
        $user->delete();
        session()->flash('success',trans('users.Data Deleted Successfully'));
        return back();
    }
}

resources/views/users/layout/footer.blade.php
<!-- END MAIN CONTAINER -->

<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
<script src="{{url('/')}}/admin/assets/js/libs/jquery-3.1.1.min.js"></script>
<script src="{{url('/')}}/admin/bootstrap/js/popper.min.js"></script>
@if(app()->getLocale()=='en')
<script src="{{url('/')}}/admin/bootstrap/js/bootstrap.min.js"></script>
@else
    <script src="{{url('/')}}/admin/rtl/bootstrap/js/bootstrap.min.js"></script>

@endif
<script src="{{url('/')}}/admin/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
@if(app()->getLocale()=='en')
<script src="{{url('/')}}/admin/assets/js/app.js"></script>
@else
    <script src="{{url('/')}}/admin/rtl/assets/js/app.js"></script>

@endif
<script>
    $(document).ready(function() {
        App.init();
    });
</script>
@if(app()->getLocale()=='en')
<script src="{{url('/')}}/admin/assets/js/custom.js"></script>
@else
    <script src="{{url('/')}}/admin/rtl/assets/js/custom.js"></script>

@endif
<!-- END GLOBAL MANDATORY SCRIPTS -->

<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
<script src="{{url('/')}}/admin/plugins/apex/apexcharts.min.js"></script>
@if(app()->getLocale()=='en')
<script src="{{url('/')}}/admin/assets/js/dashboard/dash_1.js"></script>
@else
    <script src="{{url('/')}}/admin/rtl/assets/js/dashboard/dash_1.js"></script>

@endif
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
<!-- toastr -->
<script src="{{url('/')}}/admin/plugins/notification/snackbar/snackbar.min.js"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!--  BEGIN CUSTOM SCRIPTS FILE  -->
@if(app()->getLocale()=='en')
<script src="{{url('/')}}/admin/assets/js/components/notification/custom-snackbar.js"></script>
@else
    <script src="{{url('/')}}/admin/rtl/assets/js/components/notification/custom-snackbar.js"></script>

@endif
<!--  END CUSTOM SCRIPTS FILE  -->
<!-- BEGIN PAGE LEVEL CUSTOM SCRIPTS -->
<script src="{{url('/')}}/admin/plugins/table/datatable/datatables.js"></script>
<!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
<script src="{{url('/')}}/admin/plugins/table/datatable/button-ext/dataTables.buttons.min.js"></script>
<script src="{{url('/')}}/admin/plugins/table/datatable/button-ext/jszip.min.js"></script>
<script src="{{url('/')}}/admin/plugins/table/datatable/button-ext/buttons.html5.min.js"></script>
<script src="{{url('/')}}/admin/plugins/table/datatable/button-ext/buttons.print.min.js"></script>
<script>
    $('#html5-extension').DataTable( {
        "dom": "<'dt--top-section'<'row'<'col-sm-12 col-md-6 d-flex justify-content-md-start justify-content-center'B><'col-sm-12 col-md-6 d-flex justify-content-md-end justify-content-center mt-md-0 mt-3'f>>>" +
            "<'table-responsive'tr>" +
            "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
        buttons: {
            buttons: [
                { extend: 'csv', className: 'btn btn-sm',text:'{{trans('users.CSV')}}' },
                { extend: 'excel', className: 'btn btn-sm',text:'{{trans('users.Excel')}}' },
                { extend: 'print', className: 'btn btn-sm',text:'{{trans('users.Print')}}' }
            ]
        },
        "oLanguage": {
            "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
            "sInfo": "{{trans('users.SInfo')}}",
            "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
            "sSearchPlaceholder": "{{trans('users.Search')}}",
            "sLengthMenu": "{{trans('users.LengthMenu')}}",
        },
        "stripeClasses": [],
        "lengthMenu": [7, 10, 20, 50],
        "pageLength": 7
    } );
</script>
@stack('js')
</body>

</html>

resources/views/users/layout/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>{{isset($title) ? $title : trans('users.Dashboard')}}</title>
    <link rel="icon" type="image/x-icon" href="{{url('/')}}/admin/assets/img/favicon.ico"/>
    <link href="{{url('/')}}/admin/assets/css/loader.css" rel="stylesheet" type="text/css" />
    <script src="{{url('/')}}/admin/assets/js/loader.js"></script>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
    @if(app()->getLocale()=='en')
        <link href="{{url('/')}}/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="{{url('/')}}/admin/assets/css/plugins.css" rel="stylesheet" type="text/css" />
    @else
        <link href="{{url('/')}}/admin/rtl/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="{{url('/')}}/admin/rtl/assets/css/plugins.css" rel="stylesheet" type="text/css" />
    @endif
    <!-- END GLOBAL MANDATORY STYLES -->

    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM STYLES -->
    <link href="{{url('/')}}/admin/plugins/apex/apexcharts.css" rel="stylesheet" type="text/css">
    @if(app()->getLocale()=='en')
        <link href="{{url('/')}}/admin/assets/css/dashboard/dash_1.css" rel="stylesheet" type="text/css" />
    @else
        <link href="{{url('/')}}/admin/rtl/assets/css/dashboard/dash_1.css" rel="stylesheet" type="text/css" />
    @endif
    <!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->
    <!-- toastr -->
    <link href="{{url('/')}}/admin/plugins/notification/snackbar/snackbar.min.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->
    <link rel="stylesheet" type="text/css" href="{{url('/')}}/admin/plugins/table/datatable/datatables.css">
    <link rel="stylesheet" type="text/css" href="{{url('/')}}/admin/plugins/table/datatable/custom_dt_html5.css">
    <link rel="stylesheet" type="text/css" href="{{url('/')}}/admin/plugins/table/datatable/dt-global_style.css">
    @stack('css')
    <!-- END PAGE LEVEL CUSTOM STYLES -->
</head>
<body  data-spy="scroll" data-target="#navSection" data-offset="140">
<!-- BEGIN LOADER -->

resources/views/users/layout/menu.blade.php
<div class="overlay"></div>
<div class="search-overlay"></div>

<!--  BEGIN SIDEBAR  -->
<div class="sidebar-wrapper sidebar-theme">

    <nav id="sidebar">
        <div class="shadow-bottom"></div>
        <ul class="list-unstyled menu-categories" id="accordionExample">
            <li class="menu">
                <a href="#dashboard" data-active="true" data-toggle="collapse" aria-expanded="true" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        <span>{{trans('users.Dashboard')}}</span>
                    </div>
                </a>
            </li>

            @if(auth()->user()->hasPermission('read_users'))
                <li class="menu">
                    <a href="#users" data-toggle="collapse" {{active_menu('users')[0]}} class="dropdown-toggle {{active_menu('users')[1]}}">
                        <div class="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                            <span>{{trans('users.Users')}}</span>
                        </div>
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                        </div>
                    </a>
                    <ul class="collapse submenu list-unstyled {{active_menu('users')[2]}}" id="users" data-parent="#accordionExample">
                        <li class="{{active_link('users')[0]}}">
                            <a href="{{aurl('users')}}"> {{trans('users.Users List')}} </a>
                        </li>
                        @if(auth()->user()->hasPermission('create_users'))
                            <li class="{{active_link('users/create')[0]}}">
                                <a href="{{route('users.create')}}"> {{trans('users.Add User')}} </a>
                            </li>
                        @endif
                    </ul>
                </li>
            @endif

            @if(auth()->user()->hasPermission('read_categories'))
                <li class="menu">
                    <a href="#categories" data-toggle="collapse" {{active_menu('categories')[0]}} class="dropdown-toggle {{active_menu('categories')[1]}}">
                        <div class="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clipboard"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"></path><rect x="8" y="2" width="8" height="4" rx="1" ry="1"></rect></svg>                            <span>{{trans('users.Categories')}}</span>
                        </div>
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                        </div>
                    </a>
                    <ul class="collapse submenu list-unstyled {{active_menu('categories')[2]}}" id="categories" data-parent="#accordionExample">
                        <li class="{{active_link('categories')[0]}}">
                            <a href="{{aurl('categories')}}"> {{trans('users.Category List')}} </a>
                        </li>
                        @if(auth()->user()->hasPermission('create_categories'))
                            <li class="{{active_link('categories/create')[0]}}">
                                <a href="{{route('categories.create')}}"> {{trans('users.Add Category')}} </a>
                            </li>
                        @endif

                        @if(auth()->user()->hasPermission('create_categories'))
                            <li class="{{active_link('categories/multi_add')[0]}}">
                                <a href="{{aurl('categories/multi_add')}}"> {{trans('users.Multi Add Category')}} </a>
                            </li>
                        @endif
                    </ul>
                </li>
            @endif
            @if(auth()->user()->hasPermission('read_products'))
                <li class="menu">
                    <a href="#products" data-toggle="collapse" {{active_menu('products')[0]}} class="dropdown-toggle {{active_menu('products')[1]}}">
                        <div class="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-monitor"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line></svg>                            <span>{{trans('users.Products')}}</span>
                        </div>
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                        </div>
                    </a>
                    <ul class="collapse submenu list-unstyled {{active_menu('products')[2]}}" id="products" data-parent="#accordionExample">
                        <li class="{{active_link('products')[0]}}">
                            <a href="{{aurl('products')}}"> {{trans('users.Products List')}} </a>
                        </li>
                        @if(auth()->user()->hasPermission('create_products'))
                            <li class="{{active_link('products/create')[0]}}">
                                <a href="{{route('products.create')}}"> {{trans('users.Add Product')}} </a>
                            </li>
                        @endif

                        @if(auth()->user()->hasPermission('create_products'))
                            <li class="{{active_link('products/multi_add')[0]}}">
                                <a href="{{aurl('products/multi_add')}}"> {{trans('users.Multi Add Product')}} </a>
                            </li>
                        @endif
                    </ul>
                </li>
            @endif

            @if(auth()->user()->hasPermission('read_orders'))
                <li class="menu">
                    <a href="#orders" data-toggle="collapse" {{active_menu('orders')[0]}} class="dropdown-toggle {{active_menu('orders')[1]}}">
                        <div class="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-plus"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="12" y1="18" x2="12" y2="12"></line><line x1="9" y1="15" x2="15" y2="15"></line></svg>                            <span>{{trans('users.Orders')}}</span>
                        </div>
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                        </div>
                    </a>
                    <ul class="collapse submenu list-unstyled {{active_menu('orders')[2]}}" id="orders" data-parent="#accordionExample">
                        <li class="{{active_link('orders')[0]}}">
                            <a href="{{aurl('orders')}}"> {{trans('users.Orders List')}} </a>
                        </li>
                        @if(auth()->user()->hasPermission('create_orders'))
                            <li class="{{active_link('orders/create')[0]}}">
                                <a href="{{route('orders.create')}}"> {{trans('users.Add Order')}} </a>
                            </li>
                        @endif
                    </ul>
                </li>
            @endif

        </ul>

    </nav>

</div>
<!--  END SIDEBAR  -->