routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>'serialNumber'],function(){
    //add language prefix
    Route::group(
        [
            'prefix' => LaravelLocalization::setLocale(),
            'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
        ], function(){


        //add middleware guest to all route
        Route::group(['middleware'=>'guest'],function(){
            //add namespace user to all route
            Route::group(['namespace'=>'User'],function(){
                //route to function that return login view
                Route::get('login','UserAuthController@login')->name('login');
                //route to function that handle users login
                Route::post('login','UserAuthController@do_login')->name('do_login');
                //route to function that return forget password view
                Route::get('forget/password','UserAuthController@forget_password')->name('forget_password');
                //route to function that handle create token for user
                Route::post('forget/password','UserAuthController@forget_password_post')->name('forget_password_post');
                //route to function that return reset password view
                Route::get('reset/password/{token}','UserAuthController@reset_password')->name('reset_password');
                //route to function that reset user password
                Route::post('reset/password/{token}','UserAuthController@reset_password_final')->name('reset_password_final');
            });
        });


        //assign middleware to all route
        Route::group(['middleware'=>'auth:web'],function(){
            //redirect route to dashboard
            Route::redirect('/','dashboard');

            //prefix all route with dashboard
            Route::group(['prefix'=>'dashboard'],function(){
                //route to return home view
                Route::get('/',function(){
                    return view('users.index',['title'=>trans('users.Dashboard')]);
                });

                //route to users resource
                Route::namespace('User')->group(function(){
                    Route::get('users/delete/{id}','UserController@destroy')->name('delete_users');
                    Route::resource('users','UserController');
                    //rotue to logout function that handle user logout

                    Route::any('logout','UserAuthController@logout')->name('logout');

                });
                //route to resource category
                Route::namespace('Category')->group(function(){
                    Route::get('categories/multi_add','CategoryController@multi_add')->name('multi_add');
                    Route::post('categories/multi_add','CategoryController@multi_store')->name('categories_multi_add_store');
                    Route::get('categories/multi_delete','CategoryController@multi_delete')->name('category_multi_delete');
                    Route::get('categories/delete/{id}','CategoryController@destroy')->name('delete_categories');
                    Route::resource('categories','CategoryController');
                });


                //route to resource products
                Route::namespace('Product')->group(function(){
                    Route::get('products/category','ProductController@getcategory')->name('getCategory');
                    Route::get('products/multi_add','ProductController@multi_add')->name('multi_add');
                    Route::post('products/multi_add','ProductController@multi_store')->name('products_multi_add_store');
                    Route::get('products/multi_delete','ProductController@multi_delete')->name('products_multi_delete');
                    Route::get('products/delete/{id}','ProductController@destroy')->name('delete_products');
                    Route::resource('products','ProductController');
                });


                //route to resource products
                Route::namespace('Order')->group(function(){
                    Route::get('orders/multi_add','OrderController@multi_add')->name('multi_add');
                    Route::post('orders/multi_add','OrderController@multi_store')->name('orders_multi_add_store');
                    Route::get('orders/delete/{id}','OrderController@destroy')->name('delete_orders');
                    Route::resource('orders','OrderController');
                });

            });
        });




    });
});
Route::get('notfound',function(){
    return view('users.notFound',['title'=>trans('users.Not Found')]);
})->name('notFound');

app/Http/Controllers/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Category;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryStore;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware(['permission:read_categories'])->only('index');
        $this->middleware(['permission:create_categories'])->only('create');
        $this->middleware(['permission:update_categories'])->only('edit');
        $this->middleware(['permission:delete_categories'])->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('users.categories.index',['title'=>trans('users.Category List'),'categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.categories.create',['title'=>trans('users.Add Category')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStore $request)
    {
        $request->validated();
        $category = new Category();
        $category->name = ['en'=>$request->name_en,'ar'=>$request->name_ar];
        $category->save();
        session()->flash('success',trans('users.Data Saved Successfully'));
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('users.categories.edit',['title'=>trans('users.Category Edit'),'category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryStore $request, $id)
    {
        $request->validated();
        $category = Category::find($id);
        $category->update([
            $category->name = ['en'=>$request->name_en,'ar'=>$request->name_ar],
        ]);
        session()->flash('success',trans('users.Data Updated Successfully'));
        return redirect(aurl('categories'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();
        session()->flash('success',trans('users.Data Deleted Successfully'));
        return back();
    }

    public function multi_delete(Request $request){
        $items = $request->items;
        if(!empty($items)){
            if(is_array($items)){
                Category::destroy($items);
            }else{
                Category::delete($items);
            }
            session()->flash('success',trans('users.Data Deleted Successfully'));
            return back();
        }else{
            session()->flash('error',trans('users.You Must Choose Some Record'));
            return back();
        }
    }

    public function multi_add(){
        return view('users.categories.mutli_add',['title'=>trans('users.Multi Add Category')]);
    }
    public function multi_store(Request $request){
        $data = $request->validate([
            'category_list.*.name_ar'=>'required|unique:categories,name->ar',
            'category_list.*.name_en'=>'required|unique:categories,name->en',
        ]);

        $category_list = $request->category_list;
        foreach ($category_list as $list){
            $category = new Category();
            $category->name = ['en'=>$list['name_en'],'ar'=>$list['name_ar']];
            $category->save();
        }
        session()->flash('success',trans('users.Data Saved Successfully'));
        return redirect(aurl('categories'));
    }
}

app/Http/Controllers/User/UserAuthController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Mail\UserResetPassword;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Validation\Rule;

class UserAuthController extends Controller
{
    //function to return login view
    public function login(){
        return view('users.login',['title'=>trans('users.Login')]);
    }

    //function to handle users login
    public function do_login(Request $request){
        $remember_me = $request->remember_me == 1 ? true : false;
        if(admin()->attempt(['email'=>$request->email,'password'=>$request->password],$remember_me)){
            session()->flash('success',trans('users.You Are Logged In Successfully'));
            return redirect(aurl());
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to handle user logout
    public function logout(){
        admin()->logout();
        session()->flash('success',trans('users.You Are Logged Out Successfully'));
        return redirect('login');
    }

    //function to return forget password view
    public function forget_password(){
        return view('users.forget_password',['title'=>trans('users.Forgot Password?')]);
    }

    //function to create token for user
    public function forget_password_post(Request $request){
        $user = User::where('email',$request->email)->first();
        if(!empty($user)){
            $token = app('auth.password.broker')->createToken($user);
            $data = DB::table('password_resets')->insert([
                'email'=>$user->email,
                'token'=>$token,
                'created_at'=>Carbon::now()
            ]);
            Mail::to($user->email)->send(new UserResetPassword(['data'=>$user,'token'=>$token]));
            session()->flash('success',trans('users.Reset Link Sent Successfully'));
            return back()->withInput();
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to return reset password view
    public function reset_password($token){
        $check_token = DB::table('password_resets')->where('token',$token)->where('created_at','>',Carbon::now()->subHours(2))->first();
        if(!empty($check_token)){
            return view('users.reset_password',['title'=>trans('users.Reset Password'),'data'=>$check_token]);
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to reset user password
    public function reset_password_final(Request $request,$token){
        $check_token = DB::table('password_resets')->where('token',$token)->where('created_at','>',Carbon::now()->subHours(2))->first();
        $request->validate([
            'email'=>['required',Rule::in($check_token->email)],
            'password'=>'required|confirmed|min:9',
            'password_confirmation'=>'required'
        ]);
        if(!empty($check_token)){
            $user = User::where('email',$check_token->email)->update([
                'email'=>$check_token->email,
                'password'=>bcrypt($request->password)
            ]);
            DB::table('password_resets')->where('email',$request->email)->delete();
            $serialNumber = SerialNumber();
            admin()->attempt(['email'=>$check_token->email,'password'=>$request->password,'serialNumber'=>$serialNumber],true);
            session()->flash('success',trans('users.Password Reset Successfully'));
            return redirect(aurl());
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserStore;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware(['permission:read_users'])->only('index');
        $this->middleware(['permission:create_users'])->only('create');
        $this->middleware(['permission:update_users'])->only('edit');
        $this->middleware(['permission:delete_users'])->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::whereRoleIs('admin')->get();
        return view('users.users.index',['title'=>trans('users.Users List'),'users'=>$users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.users.create',['title'=>trans('users.Add User')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStore $request)
    {
        $serialNumber = serialNumber();
        $data = $request->validated();
        if($request->image){
            Image::make($request->image)->resize(300,null,function($constraint){
                $constraint->aspectRatio();
            })->save(public_path('uploads/users/'.$request->image->hashName()));
            $data['image'] = $request->image->hashName();
        }
        if($request->password){
            $data['password'] = bcrypt($request->password);
        }
        $user = User::create($data);
        $user->attachRole('admin');
        $user->syncPermissions($request->permissions);
        session()->flash('success',trans('users.Data Saved Successfully'));
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('users.users.edit',['title'=>trans('users.User Edit'),'user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'name'=>'required|min:5',
            'email'=>['required',Rule::unique('users','email')->ignore($id,'id')],
            'password'=>'sometimes|nullable|min:9',
            'permissions'=>'required|array|min:1',
            'image'=>'mimes:jpeg,gif,jpg,png',
        ]);
        $user = User::find($id);
        if($request->has('password')){
            $data['password'] = bcrypt($request->password);
        }
        if($request->image){
            if($request->image !='default.png'){
                Storage::disk('public_uploads')->delete('users/'.$user->image);
            }

            Image::make($request->image)->resize(300,null,function($constraint){
                $constraint->aspectRatio();
            })->save(public_path('uploads/users/'.$request->image->hashName()));
            $data['image'] = $request->image->hashName();
        }
        $user->update($data);
        $user->syncPermissions($request->permissions);
        session()->flash('success',trans('users.Data Updated Successfully'));
        return redirect(aurl('users'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if($user->image!='default.png'){
            Storage::disk('public_uploads')->delete('users/'.$user->image);
        }
        $user->delete();
        session()->flash('success',trans('users.Data Deleted Successfully'));
        return back();
    }
}

resources/views/users/categories/create.blade.php
@extends('users.home')
@push('css')
    <link href="{{url('/')}}/admin/assets/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')
    <div class="row layout-top-spacing">


        <div class="col-lg-12 col-12  layout-spacing">
            @include('users.layout.message')

            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>{{$title}}</h4>
                        </div>
                    </div>
                </div>

                <div class="widget-content">

                    <form method="post" action="{{route('categories.store')}}">
                        {{csrf_field()}}
                        <div class="form-group mb-4">
                            <label for="name_ar">{{trans('users.Arabic Name')}}</label>
                            <input type="text" name="name_ar" class="form-control" id="name_ar" placeholder="{{trans('users.Arabic Name')}}" value="{{old('name_ar')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="name_en">{{trans('users.English Name')}}</label>
                            <input type="text" name="name_en" class="form-control" id="name_en" placeholder="{{trans('users.English Name')}}" value="{{old('name_en')}}">
                        </div>
                        <button type="submit" class="btn btn-info">{{trans('users.Save')}}</button>
                        <a href="{{aurl('categories')}}" class="btn btn-danger">{{trans('users.Cancel')}}</a>
                    </form>

                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/users/categories/edit.blade.php
@extends('users.home')
@push('css')
    <link href="{{url('/')}}/admin/assets/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')
    <div class="row layout-top-spacing">


        <div class="col-lg-12 col-12  layout-spacing">
            @include('users.layout.message')

            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>{{$title}}</h4>
                        </div>
                    </div>
                </div>

                <div class="widget-content">

                    <form method="post" action="{{route('categories.update',$category->id)}}">
                        @method('put')
                        {{csrf_field()}}
                        <input type="hidden" name="id" value="{{$category->id}}">
                        <div class="form-group mb-4">
                            <label for="name_ar">{{trans('users.Arabic Name')}}</label>
                            <input type="text" name="name_ar" class="form-control" id="name_ar" placeholder="{{trans('users.Arabic Name')}}" value="{{$category->getTranslation('name','ar')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="name_en">{{trans('users.English Name')}}</label>
                            <input type="text" name="name_en" class="form-control" id="name_en" placeholder="{{trans('users.English Name')}}" value="{{$category->getTranslation('name','en')}}">
                        </div>
                        <a href="{{aurl('categories')}}" class="btn btn-danger">{{trans('users.Cancel')}}</a>
                        <button type="submit" class="btn btn-info">{{trans('users.update')}}</button>
                    </form>

                </div>
            </div>
        </div>

    </div>
    @push('js')
        <script>
            $('.image').on('change',function(){
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('.img-preview').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(this.files[0]);
                } else {
                    $('.img-preview').attr('src', '');
                }
            });
        </script>
    @endpush
@endsection

resources/views/users/categories/index.blade.php
@extends('users.home')
@push('css')
    <link href="{{url('/')}}/admin/plugins/animate/animate.css" rel="stylesheet" type="text/css" />
    <script src="{{url('/')}}/admin/plugins/sweetalerts/promise-polyfill.js"></script>
    <link href="{{url('/')}}/admin/plugins/sweetalerts/sweetalert2.min.css" rel="stylesheet" type="text/css" />
    <link href="{{url('/')}}/admin/plugins/sweetalerts/sweetalert.css" rel="stylesheet" type="text/css" />
    <link href="{{url('/')}}/admin/assets/css/components/custom-sweetalert.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')

    <div class="row layout-top-spacing">

        @include('users.layout.message')
        <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
            <form action="{{route('category_multi_delete')}}" id="mutlidel">
                {{csrf_field()}}
                @if(auth()->user()->hasPermission('delete_categories'))
                <button type="submit" class="btn btn-danger mb-3 multidel">{{trans('users.Delete Selected')}}</button>
                @else
                <button type="button" class="btn btn-danger mb-3 disabled">{{trans('users.Delete Selected')}}</button>

                @endif

                <div class="widget-content widget-content-area br-6">
                        <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
                            <thead>
                            <tr>
                                @if(auth()->user()->hasPermission('delete_categories'))
                                    <th class="dt-no-sorting"><input type="checkbox" class="check_all"></th>
                                @endif
                                <th>{{trans('users.ID')}}</th>
                                <th>{{trans('users.Name')}}</th>
                                <th>{{trans('users.Related Products')}}</th>
                                <th class="dt-no-sorting">{{trans('users.Action')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    @if(auth()->user()->hasPermission('delete_categories'))
                                    <td><input type="checkbox" name="items[]" class="items_checkbox" value="{{$category->id}}"></td>
                                    @endif
                                    <td>{{$category->id}}</td>
                                    <td>{{$category->name}}</td>
                                        <td><a href="{{route('getCategory',['category_id'=>$category->id])}}" class="btn btn-primary">{{trans('users.Related Products')}}</a></td>
                                    <td>
                                        @if(auth()->user()->hasPermission('update_categories'))
                                            <a href="{{route('categories.edit',$category->id)}}" class="btn btn-success">{{trans('users.Edit')}}</a>
                                        @else
                                            <a href="#" class="btn btn-success disabled">{{trans('users.Edit')}}</a>
                                        @endif
                                        @if(auth()->user()->hasPermission('delete_categories'))
                                            <a href="{{route('delete_categories',$category->id)}}" class="btn btn-danger delbtn">{{trans('users.Delete')}}</a>
                                        @else
                                            <a href="#" class="btn btn-danger disabled">{{trans('users.Delete')}}</a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                </div>
            </form>

        </div>

    </div>

    @push('js')
        <script src="{{url('/')}}/admin/plugins/sweetalerts/sweetalert2.min.js"></script>
        <script src="{{url('/')}}/admin/plugins/sweetalerts/custom-sweetalert.js"></script>
        <!-- END THEME GLOBAL STYLE -->
        <script>
            $('.delbtn').on('click', function (e) {
                e.preventDefault();
                var link = $(this).attr('href');
                const swalWithBootstrapButtons = swal.mixin({
                    confirmButtonClass: 'btn btn-success btn-rounded',
                    cancelButtonClass: 'btn btn-danger btn-rounded mr-3',
                    buttonsStyling: false,
                })

                swalWithBootstrapButtons({
                    title: '{{trans('users.Are you sure?')}}',
                    text: "{{trans('users.You wont be able to revert this!')}}",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: '{{trans('users.Yes, delete it!')}}',
                    cancelButtonText: '{{trans('users.No, cancel!')}}',
                    reverseButtons: true,
                    padding: '2em'
                }).then(function(result) {
                    if (result.value) {
                        window.location.href = link;
                    } else if (
                        // Read more about handling dismissals
                        result.dismiss === swal.DismissReason.cancel
                    ) {
                        swalWithBootstrapButtons(
                            '{{trans('users.Cancelled')}}',
                            '{{trans('users.Your imaginary file is safe :)')}}',
                            'error'
                        )
                    }
                })
            })
        </script>

        <script>
            $(document).on('click','.check_all',function(){
                $('input[class="items_checkbox"]:checkbox').each(function(){
                    if($('input[class="check_all"]:checkbox:checked').length == 0){
                        $(this).prop('checked',false);
                    }else{
                        $(this).prop('checked',true);
                    }
                })
            });
        </script>
        <script>
            $('.multidel').on('click', function (e) {
                e.preventDefault();
                const swalWithBootstrapButtons = swal.mixin({
                    confirmButtonClass: 'btn btn-success btn-rounded',
                    cancelButtonClass: 'btn btn-danger btn-rounded mr-3',
                    buttonsStyling: false,
                })

                swalWithBootstrapButtons({
                    title: '{{trans('users.Are you sure?')}}',
                    text: "{{trans('users.You wont be able to revert this!')}}",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: '{{trans('users.Yes, delete it!')}}',
                    cancelButtonText: '{{trans('users.No, cancel!')}}',
                    reverseButtons: true,
                    padding: '2em'
                }).then(function(result) {
                    if (result.value) {
                        $('#mutlidel').submit();
                    } else if (
                        // Read more about handling dismissals
                        result.dismiss === swal.DismissReason.cancel
                    ) {
                        swalWithBootstrapButtons(
                            '{{trans('users.Cancelled')}}',
                            '{{trans('users.Your imaginary file is safe :)')}}',
                            'error'
                        )
                    }
                })
            })
        </script>
    @endpush
@endsection