routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>'serialNumber'],function(){
    //add language prefix
    Route::group(
        [
            'prefix' => LaravelLocalization::setLocale(),
            'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
        ], function(){


        //add middleware guest to all route
        Route::group(['middleware'=>'guest'],function(){
            //add namespace user to all route
            Route::group(['namespace'=>'User'],function(){
                //route to function that return login view
                Route::get('login','UserAuthController@login')->name('login');
                //route to function that handle users login
                Route::post('login','UserAuthController@do_login')->name('do_login');
                //route to function that return forget password view
                Route::get('forget/password','UserAuthController@forget_password')->name('forget_password');
                //route to function that handle create token for user
                Route::post('forget/password','UserAuthController@forget_password_post')->name('forget_password_post');
                //route to function that return reset password view
                Route::get('reset/password/{token}','UserAuthController@reset_password')->name('reset_password');
                //route to function that reset user password
                Route::post('reset/password/{token}','UserAuthController@reset_password_final')->name('reset_password_final');
            });
        });


        //assign middleware to all route
        Route::group(['middleware'=>'auth:web'],function(){
            //redirect route to dashboard
            Route::redirect('/','dashboard');

            //prefix all route with dashboard
            Route::group(['prefix'=>'dashboard'],function(){
                //route to return home view
                Route::get('/',function(){
                    return view('users.index',['title'=>trans('users.Dashboard')]);
                });

                //route to users resource
                Route::namespace('User')->group(function(){
                    Route::get('users/delete/{id}','UserController@destroy')->name('delete_users');
                    Route::resource('users','UserController');
                    //rotue to logout function that handle user logout

                    Route::any('logout','UserAuthController@logout')->name('logout');

                });
                //route to resource category
                Route::namespace('Category')->group(function(){
                    Route::get('categories/multi_add','CategoryController@multi_add')->name('multi_add');
                    Route::post('categories/multi_add','CategoryController@multi_store')->name('categories_multi_add_store');
                    Route::get('categories/multi_delete','CategoryController@multi_delete')->name('category_multi_delete');
                    Route::get('categories/delete/{id}','CategoryController@destroy')->name('delete_categories');
                    Route::resource('categories','CategoryController');
                });


                //route to resource products
                Route::namespace('Product')->group(function(){
                    Route::get('products/category','ProductController@getcategory')->name('getCategory');
                    Route::get('products/multi_add','ProductController@multi_add')->name('multi_add');
                    Route::post('products/multi_add','ProductController@multi_store')->name('products_multi_add_store');
                    Route::get('products/multi_delete','ProductController@multi_delete')->name('products_multi_delete');
                    Route::get('products/delete/{id}','ProductController@destroy')->name('delete_products');
                    Route::resource('products','ProductController');
                });


                //route to resource products
                Route::namespace('Order')->group(function(){
                    Route::get('orders/multi_add','OrderController@multi_add')->name('multi_add');
                    Route::post('orders/multi_add','OrderController@multi_store')->name('orders_multi_add_store');
                    Route::get('orders/delete/{id}','OrderController@destroy')->name('delete_orders');
                    Route::resource('orders','OrderController');
                });

            });
        });




    });
});
Route::get('notfound',function(){
    return view('users.notFound',['title'=>trans('users.Not Found')]);
})->name('notFound');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Product extends Model
{
    use HasFactory,HasTranslations;
    protected $table = 'products';
    protected $fillable = ['name','category_id','stock','sale_price','purchase_price','image'];
    protected $translatable = ['name'];
    protected $appends = ['image_path','profit_percent'];
    public function getImagePathAttribute(){
        return asset('uploads/products/'.$this->image);
    }

    public function getProfitPercentAttribute(){
        $profit = $this->sale_price - $this->purchase_price;
        $profit_percent = $profit * 100 / $this->purchase_price;
        return $profit_percent;
    }

    public function category(){
        return $this->belongsTo(Category::class,'category_id');
    }

    public function orders(){
        return $this->belongsTo(Order::class,'product_order');
    }
}

app/Http/Controllers/Product/ProductController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware(['permission:read_products'])->only('index');
        $this->middleware(['permission:create_products'])->only('create');
        $this->middleware(['permission:update_products'])->only('edit');
        $this->middleware(['permission:delete_products'])->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $categories = Category::all();
        return view('users.products.index',['title'=>trans('users.Products List'),'products'=>$products,'categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('users.products.create',['title'=>trans('users.Add Product'),'categories'=>$categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $data = $request->validated();
        $prodcut = new Product();
        $prodcut->name = ['en'=>$request->name_en,'ar'=>$request->name_ar];
        $prodcut->category_id = $request->category_id;
        $prodcut->stock = $request->stock;
        $prodcut->sale_price = $request->sale_price;
        $prodcut->purchase_price = $request->purchase_price;
        if($request->image){
            Image::make($request->image)->resize(300,null,function($constraint){
                $constraint->aspectRatio();
            })->save(public_path('uploads/products/'.$request->image->hashName()));
            $prodcut['image'] = $request->image->hashName();
        }
        $prodcut->save();
        session()->flash('success',trans('users.Data Saved Successfully'));
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $categories = Category::all();
        return view('users.products.edit',['title'=>trans('users.Product Edit'),'product'=>$product,'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        $request->validated();
        $product = Product::find($id);
        $product->name = ['en'=>$request->name_en,'ar'=>$request->name_ar];
        $product->category_id = $request->category_id;
        $product->sale_price = $request->sale_price;
        $product->purchase_price = $request->purchase_price;
        $product->stock = $request->stock;
        if($request->image){
            if($product->image != 'default.png'){
                Storage::disk('public_uploads')->delete('products/'.$product->image);
            }

            Image::make($request->image)->resize(300,null,function($constraint){
                $constraint->aspectRatio();
            })->save(public_path('uploads/products/'.$request->image->hashName()));
            $product['image'] = $request->image->hashName();
        }
        $product->save();
        session()->flash('success',trans('users.Data Updated Successfully'));
        return redirect(aurl('products'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        if($product->image!='default.png'){
            Storage::disk('public_uploads')->delete('products/'.$product->image);
        }
        $product->delete();
        session()->flash('success',trans('users.Data Deleted Successfully'));
        return back();
    }

    public function multi_delete(Request $request){
        $items = $request->items;
        if(!empty($items)){
            if(is_array($items)){
                foreach ($items as $item){
                    $product = Product::find($item);
                    if($product->image !='default.png'){
                        Storage::disk('public_uploads')->delete('products/'.$product->image);
                    }
                    Product::where('id',$product->id)->delete();
                }
                session()->flash('success',trans('admin.Data Deleted Successfully'));
                return redirect(aurl('products'));

            }else{
                Product::delete($items);
                session()->flash('success',trans('admin.Data Deleted Successfully'));
                return redirect(aurl('products'));
            }
        }else{
            session()->flash('error',trans('users.You Must Choose Some Record'));
            return back();
        }
    }

    public function getcategory(Request $request){
        $categories = Category::all();
        $category_id = $request->category_id;
        if($category_id!=0){
            $products = Product::where('category_id',$request->category_id)->get();
            return view('users.products.index',['title'=>trans('users.Products List'),'products'=>$products,'categories'=>$categories]);
        }else{
            $products = Product::all();
            return view('users.products.index',['title'=>trans('users.Products List'),'products'=>$products,'categories'=>$categories]);
        }

    }

    public function multi_add(){
        $categories = Category::all();
        return view('users.products.multi_add',['title'=>trans('users.Multi Add Product'),'categories'=>$categories]);
    }

    public function multi_store(Request $request)
    {
        $request->validate([
            'products_list.*.name_en' => 'required',
            'products_list.*.name_ar' => 'required',
            'products_list.*.category_id' => 'required|exists:categories,id',
            'products_list.*.purchase_price' => 'required',
            'products_list.*.sale_price' => 'required',
            'products_list.*.stock' => 'required',
        ]);
        $list_products = $request->products_list;
        foreach ($list_products as $list) {
            $product = new Product();
            $product->name = ['en' => $list['name_en'], 'ar' => $list['name_ar']];
            $product->category_id = $list['category_id'];
            $product->purchase_price = $list['purchase_price'];
            $product->sale_price = $list['sale_price'];
            $product->stock = $list['stock'];
            $product->save();
        }
        session()->flash('success', trans('users.Data Saved Successfully'));
        return redirect(aurl('products'));
    }
}

app/Http/Controllers/User/UserAuthController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Mail\UserResetPassword;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Validation\Rule;

class UserAuthController extends Controller
{
    //function to return login view
    public function login(){
        return view('users.login',['title'=>trans('users.Login')]);
    }

    //function to handle users login
    public function do_login(Request $request){
        $remember_me = $request->remember_me == 1 ? true : false;
        if(admin()->attempt(['email'=>$request->email,'password'=>$request->password],$remember_me)){
            session()->flash('success',trans('users.You Are Logged In Successfully'));
            return redirect(aurl());
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to handle user logout
    public function logout(){
        admin()->logout();
        session()->flash('success',trans('users.You Are Logged Out Successfully'));
        return redirect('login');
    }

    //function to return forget password view
    public function forget_password(){
        return view('users.forget_password',['title'=>trans('users.Forgot Password?')]);
    }

    //function to create token for user
    public function forget_password_post(Request $request){
        $user = User::where('email',$request->email)->first();
        if(!empty($user)){
            $token = app('auth.password.broker')->createToken($user);
            $data = DB::table('password_resets')->insert([
                'email'=>$user->email,
                'token'=>$token,
                'created_at'=>Carbon::now()
            ]);
            Mail::to($user->email)->send(new UserResetPassword(['data'=>$user,'token'=>$token]));
            session()->flash('success',trans('users.Reset Link Sent Successfully'));
            return back()->withInput();
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to return reset password view
    public function reset_password($token){
        $check_token = DB::table('password_resets')->where('token',$token)->where('created_at','>',Carbon::now()->subHours(2))->first();
        if(!empty($check_token)){
            return view('users.reset_password',['title'=>trans('users.Reset Password'),'data'=>$check_token]);
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }

    //function to reset user password
    public function reset_password_final(Request $request,$token){
        $check_token = DB::table('password_resets')->where('token',$token)->where('created_at','>',Carbon::now()->subHours(2))->first();
        $request->validate([
            'email'=>['required',Rule::in($check_token->email)],
            'password'=>'required|confirmed|min:9',
            'password_confirmation'=>'required'
        ]);
        if(!empty($check_token)){
            $user = User::where('email',$check_token->email)->update([
                'email'=>$check_token->email,
                'password'=>bcrypt($request->password)
            ]);
            DB::table('password_resets')->where('email',$request->email)->delete();
            $serialNumber = SerialNumber();
            admin()->attempt(['email'=>$check_token->email,'password'=>$request->password,'serialNumber'=>$serialNumber],true);
            session()->flash('success',trans('users.Password Reset Successfully'));
            return redirect(aurl());
        }else{
            session()->flash('error',trans('users.Sorry There Were An Error'));
            return back()->withInput();
        }
    }
}

resources/views/users/products/create.blade.php
@extends('users.home')
@push('css')
    <link href="{{url('/')}}/admin/assets/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')
    <div class="row layout-top-spacing">


        <div class="col-lg-12 col-12  layout-spacing">
            @include('users.layout.message')

            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>{{$title}}</h4>
                        </div>
                    </div>
                </div>

                <div class="widget-content">

                    <form method="post" action="{{route('products.store')}}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="form-group mb-4">
                            <label for="name_ar">{{trans('users.Arabic Name')}}</label>
                            <input type="text" name="name_ar" class="form-control" id="name_ar" placeholder="{{trans('users.Arabic Name')}}" value="{{old('name_ar')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="name_en">{{trans('users.English Name')}}</label>
                            <input type="text" name="name_en" class="form-control" id="name_en" placeholder="{{trans('users.English Name')}}" value="{{old('name_en')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="category_id">{{trans('users.Category')}}</label>
                            <select class="form-control" name="category_id" id="category_id">
                                <option value="0">{{trans('users.Category')}}</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group mb-4">
                            <label for="sale_price">{{trans('users.Sale Price')}}</label>
                            <input type="text" name="sale_price" class="form-control" id="sale_price" placeholder="{{trans('users.Sale Price')}}" value="{{old('sale_price')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="sale_price">{{trans('users.Purchase Price')}}</label>
                            <input type="text" name="purchase_price" class="form-control" id="purchase_price" placeholder="{{trans('users.Purchase Price')}}" value="{{old('purchase_price')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="stock">{{trans('users.Stock')}}</label>
                            <input type="number" min="1" name="stock" class="form-control" id="stock" placeholder="{{trans('users.Stock')}}" value="{{old('stock')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="image">{{trans('users.Image')}}</label>
                            <input type="file" class="form-control-file image" id="image" name="image">
                        </div>

                        <div class="form-group mb-4">
                            <label for="image">{{trans('users.Image Preview')}}</label>
                            <img src="{{asset('uploads/products/default.png')}}" width="100px" height="100px" class="img-thumbnail img-preview">
                        </div>

                        <button type="submit" class="btn btn-info">{{trans('users.Save')}}</button>
                        <a href="{{aurl('categories')}}" class="btn btn-danger">{{trans('users.Cancel')}}</a>
                    </form>

                </div>
            </div>
        </div>

    </div>
    @push('js')
        <script>
            $('.image').on('change',function(){
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('.img-preview').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(this.files[0]);
                } else {
                    $('.img-preview').attr('src', '');
                }
            });
        </script>
    @endpush
@endsection

resources/views/users/products/edit.blade.php
@extends('users.home')
@push('css')
    <link href="{{url('/')}}/admin/assets/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')
    <div class="row layout-top-spacing">


        <div class="col-lg-12 col-12  layout-spacing">
            @include('users.layout.message')

            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>{{$title}}</h4>
                        </div>
                    </div>
                </div>

                <div class="widget-content">

                    <form method="post" action="{{route('products.update',$product->id)}}" enctype="multipart/form-data">
                        @method('put')
                        {{csrf_field()}}
                        <input type="hidden" name="id" value="{{$product->id}}">
                        <div class="form-group mb-4">
                            <label for="name_ar">{{trans('users.Arabic Name')}}</label>
                            <input type="text" name="name_ar" class="form-control" id="name_ar" placeholder="{{trans('users.Arabic Name')}}" value="{{$product->getTranslation('name','ar')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="name_en">{{trans('users.English Name')}}</label>
                            <input type="text" name="name_en" class="form-control" id="name_en" placeholder="{{trans('users.English Name')}}" value="{{$product->getTranslation('name','en')}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="category_id">{{trans('users.Category')}}</label>
                            <select class="form-control" name="category_id" id="category_id">
                                <option value="0">{{trans('users.Category')}}</option>
                                @foreach($categories as $category)
                                    <option {{$product->category_id == $category->id ? 'selected':''}} value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group mb-4">
                            <label for="sale_price">{{trans('users.Sale Price')}}</label>
                            <input type="text" name="sale_price" class="form-control" id="sale_price" placeholder="{{trans('users.Sale Price')}}" value="{{$product->sale_price}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="sale_price">{{trans('users.Purchase Price')}}</label>
                            <input type="text" name="purchase_price" class="form-control" id="purchase_price" placeholder="{{trans('users.Purchase Price')}}" value="{{$product->purchase_price}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="stock">{{trans('users.Stock')}}</label>
                            <input type="number" min="1" name="stock" class="form-control" id="stock" placeholder="{{trans('users.Stock')}}" value="{{$product->stock}}">
                        </div>

                        <div class="form-group mb-4">
                            <label for="image">{{trans('users.Image')}}</label>
                            <input type="file" class="form-control-file image" id="image" name="image">
                        </div>

                        <div class="form-group mb-4">
                            <label for="image">{{trans('users.Image Preview')}}</label>
                            <img src="{{$product->image_path}}" width="100px" height="100px" class="img-thumbnail img-preview">
                        </div>

                        <a href="{{aurl('products')}}" class="btn btn-danger">{{trans('users.Cancel')}}</a>
                        <button type="submit" class="btn btn-info">{{trans('users.update')}}</button>
                    </form>

                </div>
            </div>
        </div>

    </div>
    @push('js')
        <script>
            $('.image').on('change',function(){
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('.img-preview').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(this.files[0]);
                } else {
                    $('.img-preview').attr('src', '');
                }
            });
        </script>
    @endpush
@endsection

resources/views/users/products/multi_add.blade.php
@extends('users.home')
@push('css')
    <link href="{{url('/')}}/admin/assets/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')
    <div class="row layout-top-spacing">


        <div class="col-lg-12 col-12  layout-spacing">
            @include('users.layout.message')

            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>{{$title}}</h4>
                        </div>
                    </div>
                </div>

                <div class="widget-content">

                    <form method="post" action="{{route('products_multi_add_store')}}" class="repeater">
                        {{csrf_field()}}
                            <div data-repeater-list="products_list">
                                <div data-repeater-item>
                                    <div class="row mb-4">
                                        <div class="col">
                                            <select class="form-control" name="category_id" id="category_id">
                                                <option value="0">{{trans('users.Category')}}</option>
                                                @foreach($categories as $category)
                                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="col">
                                            <input type="text" name="name_ar" class="form-control" placeholder="{{trans('users.Arabic Name')}}">
                                        </div>
                                        <div class="col">
                                            <input type="text" class="form-control" placeholder="{{trans('users.English Name')}}" name="name_en">
                                        </div>
                                        <div class="col">
                                            <input type="text" class="form-control" placeholder="{{trans('users.Purchase Price')}}" name="purchase_price">
                                        </div>
                                        <div class="col">
                                            <input type="text" class="form-control" placeholder="{{trans('users.Sale Price')}}" name="sale_price">
                                        </div>
                                        <div class="col">
                                            <input type="number" min="0" class="form-control" placeholder="{{trans('users.Stock')}}" name="stock">
                                        </div>
                                        <div class="col">
                                            <button type="button" data-repeater-delete class="btn btn-danger">-</button>
                                        </div>
                                    </div>

                                </div>
                            </div>

                        <button type="button" data-repeater-create class="btn btn-success">{{trans('users.Add')}}</button>
                        <button type="submit" class="btn btn-info">{{trans('users.Save')}}</button>
                        <a href="{{aurl('products')}}" class="btn btn-danger">{{trans('users.Cancel')}}</a>
                    </form>

                </div>
            </div>
        </div>

    </div>
    @push('js')
    <script src="{{url('/')}}/admin/assets/js/repeater.js"></script>
    @endpush

@endsection